# Configuration generated by New-ConfigurationFromSample
# Generated on: 2025-10-04 21:22:10
#
# Usage:
#   Dot-source this file to load the configuration into the $Config variable:
#       . 'C:\Users\Joshua Wilson\source\repos\PSTestableData\testoutput.ps1'
#
#   Or assign it to a custom variable:
#       $myConfig = . 'C:\Users\Joshua Wilson\source\repos\PSTestableData\testoutput.ps1'
#
# The configuration can be edited manually and then reloaded.

$Config = @{
    apiVersion = @{
        Action = 'Preserve'
        Type = 'string'
    }
    items = @{
        Action = 'Preserve'
        ArrayCount = 4
        ItemStructure = @{
            apiVersion = @{
                Action = 'Preserve'
                Type = 'string'
            }
            kind = @{
                Action = 'Preserve'
                Type = 'string'
            }
            metadata = @{
                creationTimestamp = @{
                    Action = 'Randomize'
                    Type = 'datetime'
                }
                labels = @{
                    'kubernetes.io/metadata.name' = @{
                        Action = 'Link'
                        LinkTo = 'name'
                        Type = 'string'
                    }
                }
                name = @{
                    Action = 'Randomize'
                    Type = 'string'
                }
                resourceVersion = @{
                    Action = 'Randomize'
                    Type = 'int'
                }
                uid = @{
                    Action = 'Randomize'
                    Type = 'guid'
                }
            }
            spec = @{
                finalizers = @{
                    Action = 'Preserve'
                    ArrayCount = 1
                    ItemAction = 'Preserve'
                    ItemType = 'string'
                    Type = 'array'
                }
            }
            status = @{
                phase = @{
                    Action = 'Preserve'
                    Type = 'string'
                }
            }
        }
        Type = 'array'
    }
    kind = @{
        Action = 'Preserve'
        Type = 'string'
    }
    metadata = @{
        resourceVersion = @{
            Action = 'Preserve'
            Type = 'string'
        }
    }
}

# Return the configuration when dot-sourced
return $Config
